import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import {
  canonicalSliceParamsJson,
  createSliceParamsFingerprint,
  parseDurationToSeconds,
  parsePrusaSlicerGcode,
} from "../worker/prusaslicer-result-parser.mjs";

async function createFixtureRoot() {
  return mkdtemp(join(tmpdir(), "make3d-prusaslicer-parser-"));
}

async function writeGcode(root, name, content) {
  await mkdir(root, { recursive: true });
  const filePath = join(root, name);
  await writeFile(filePath, content);
  return filePath;
}

function completeGcode(options = {}) {
  const lineEnding = options.lineEnding || "\n";
  const layers = options.layers ?? 100;
  const stats = options.stats ?? {
    filamentLength: "2116.64",
    filamentVolume: "5.09",
    filamentWeight: "0.00",
    normalTime: "24m 56s",
    silentTime: "25m 44s",
  };
  const config = options.config ?? {
    filamentType: "PLA",
    printerModel: "Bambu Lab P1S",
    nozzleDiameter: "0.4",
    layerHeight: "0.2",
  };
  const lines = [
    options.banner ?? "; generated by PrusaSlicer 2.7.2 on 2026-07-14 at 09:25:30 UTC",
    "G90",
  ];

  for (let index = 1; index <= layers; index += 1) {
    lines.push(";LAYER_CHANGE");
    lines.push(`;Z:${(index * 0.2).toFixed(2)}`);
    lines.push(`G1 Z${(index * 0.2).toFixed(2)}`);
  }

  if (options.longComment) {
    lines.push(`; ${"x".repeat(20 * 1024)}`);
  }

  const statsLines = [
    stats.filamentLength == null ? null : `; filament used [mm] = ${stats.filamentLength}`,
    stats.filamentVolume == null ? null : `; filament used [cm3] = ${stats.filamentVolume}`,
    stats.filamentWeight == null ? null : `; total filament used [g] = ${stats.filamentWeight}`,
    stats.normalTime == null ? null : `; estimated printing time (normal mode) = ${stats.normalTime}`,
    stats.silentTime == null ? null : `; estimated printing time (silent mode) = ${stats.silentTime}`,
  ].filter(Boolean);
  const configLines = [
    config.filamentType == null ? null : `; filament_type = ${config.filamentType}`,
    config.printerModel == null ? null : `; printer_model = ${config.printerModel}`,
    config.nozzleDiameter == null ? null : `; nozzle_diameter = ${config.nozzleDiameter}`,
    config.layerHeight == null ? null : `; layer_height = ${config.layerHeight}`,
    "; prusaslicer_config = end",
  ].filter(Boolean);

  if (options.fieldOrder === "config-first") {
    lines.push(...configLines, ...statsLines);
  } else {
    lines.push(...statsLines, ...configLines);
  }

  if (options.duplicate) {
    lines.push("; filament used [mm] = 3000.00");
  }

  if (options.extraTail) {
    lines.push(options.extraTail);
  }

  return `${lines.join(lineEnding)}${lineEnding}`;
}

async function parseFixture(content, options = {}) {
  const root = await createFixtureRoot();
  const filePath = await writeGcode(root, options.name || "fixture.gcode", content);
  const parsed = await parsePrusaSlicerGcode(filePath, {
    allowedRoots: [root],
    sliceParams: options.sliceParams,
    maxFileSizeBytes: options.maxFileSizeBytes,
  });
  return { root, filePath, parsed };
}

test("parses current Phase05-B synthetic cube expected metrics", async () => {
  const { parsed } = await parseFixture(completeGcode());

  assert.equal(parsed.parse.status, "parsed");
  assert.equal(parsed.result.print_time_seconds, 1496);
  assert.equal(parsed.result.silent_print_time_seconds, 1544);
  assert.equal(parsed.result.filament_length_microns, 2116640);
  assert.equal(parsed.result.filament_volume_mm3, 5090);
  assert.equal(parsed.result.filament_weight_mg, 0);
  assert.equal(parsed.result.layer_count, 100);
  assert.equal(parsed.result.max_layer_z_microns, 20000);
  assert.equal(parsed.result.filament_type, "PLA");
  assert.equal(parsed.result.printer_model, "Bambu Lab P1S");
  assert.equal(parsed.result.nozzle_diameter_microns, 400);
  assert.equal(parsed.result.layer_height_microns, 200);
  assert.equal(parsed.validation.metrics_status, "warning");
  assert.equal(parsed.validation.quote_ready, false);
  assert.ok(parsed.validation.invalid_fields.includes("filament_weight_mg"));
  assert.ok(
    parsed.validation.warnings.includes("explicit source weight is zero while filament volume is nonzero"),
  );
});

test("records metric sources and validation JSON", async () => {
  const { parsed } = await parseFixture(completeGcode());

  assert.equal(parsed.metric_sources.print_time_source, "gcode_tail_stat");
  assert.equal(parsed.metric_sources.filament_length_source, "gcode_tail_stat");
  assert.equal(parsed.metric_sources.filament_volume_source, "gcode_tail_stat");
  assert.equal(parsed.metric_sources.filament_weight_source, "gcode_tail_stat");
  assert.equal(parsed.metric_sources.layer_count_source, "derived_layer_markers");
  assert.equal(parsed.metric_sources.max_layer_z_source, "derived_z_markers");
  assert.match(parsed.metric_sources_json, /"print_time_source":"gcode_tail_stat"/);
  assert.match(parsed.metric_validation_json, /"quote_ready":false/);
});

test("missing weight stays null and is not derived from volume", async () => {
  const { parsed } = await parseFixture(
    completeGcode({ stats: { filamentLength: "2116.64", filamentVolume: "5.09", normalTime: "24m 56s", silentTime: "25m 44s" } }),
  );

  assert.equal(parsed.result.filament_weight_mg, null);
  assert.equal(parsed.metric_sources.filament_weight_source, "missing");
  assert.ok(parsed.validation.invalid_fields.includes("filament_weight_mg"));
});

test("explicit zero weight with nonzero volume is a warning and not quote ready", async () => {
  const { parsed } = await parseFixture(completeGcode());

  assert.equal(parsed.result.filament_weight_mg, 0);
  assert.equal(parsed.validation.metrics_status, "warning");
  assert.equal(parsed.validation.quote_ready, false);
});

test("missing print time is parsed but not quote ready", async () => {
  const { parsed } = await parseFixture(
    completeGcode({ stats: { filamentLength: "2116.64", filamentVolume: "5.09", filamentWeight: "1.20", silentTime: "25m 44s" } }),
  );

  assert.equal(parsed.parse.status, "parsed");
  assert.equal(parsed.result.print_time_seconds, null);
  assert.ok(parsed.validation.invalid_fields.includes("print_time_seconds"));
  assert.equal(parsed.validation.quote_ready, false);
});

test("field order changes do not affect parsing", async () => {
  const { parsed } = await parseFixture(completeGcode({ fieldOrder: "config-first" }));

  assert.equal(parsed.result.print_time_seconds, 1496);
  assert.equal(parsed.metric_sources.nozzle_diameter_source, "gcode_config");
});

test("CRLF line endings are supported", async () => {
  const { parsed } = await parseFixture(completeGcode({ lineEnding: "\r\n" }));

  assert.equal(parsed.result.layer_count, 100);
  assert.equal(parsed.result.max_layer_z_microns, 20000);
});

test("LF line endings are supported", async () => {
  const { parsed } = await parseFixture(completeGcode({ lineEnding: "\n" }));

  assert.equal(parsed.result.print_time_seconds, 1496);
});

test("empty G-code is rejected", async () => {
  const root = await createFixtureRoot();
  const filePath = await writeGcode(root, "empty.gcode", "");

  await assert.rejects(() => parsePrusaSlicerGcode(filePath, { allowedRoots: [root] }), /empty/);
});

test("HTML error pages are rejected", async () => {
  await assert.rejects(() => parseFixture("<!doctype html><html><body>bad gateway</body></html>"), /HTML/);
});

test("truncated G-code without tail stats remains parsed with missing metrics", async () => {
  const { parsed } = await parseFixture(["G90", ";LAYER_CHANGE", ";Z:0.20"].join("\n"));

  assert.equal(parsed.parse.status, "parsed");
  assert.equal(parsed.result.print_time_seconds, null);
  assert.ok(parsed.parse.missing_fields.includes("print_time_seconds"));
});

test("duplicate fields use the last value and record a warning", async () => {
  const { parsed } = await parseFixture(completeGcode({ duplicate: true }));

  assert.equal(parsed.result.filament_length_microns, 3000000);
  assert.ok(parsed.parse.warnings.some((warning) => warning.includes("duplicate fields encountered")));
});

test("abnormal duration units are rejected for that field", async () => {
  const { parsed } = await parseFixture(
    completeGcode({ stats: { filamentLength: "2116.64", filamentVolume: "5.09", filamentWeight: "1.20", normalTime: "12w", silentTime: "25m 44s" } }),
  );

  assert.equal(parsed.result.print_time_seconds, null);
  assert.ok(parsed.parse.warnings.some((warning) => warning.includes("unknown duration format")));
});

test("long comment lines are skipped with a warning", async () => {
  const { parsed } = await parseFixture(completeGcode({ longComment: true }));

  assert.equal(parsed.result.print_time_seconds, 1496);
  assert.ok(parsed.parse.warnings.includes("very long comment line skipped"));
});

test("unknown or missing PrusaSlicer banner does not fail parsing", async () => {
  const { parsed } = await parseFixture(completeGcode({ banner: "; generated by UnknownSlicer 1.0" }));

  assert.equal(parsed.slicer.banner_version, null);
  assert.equal(parsed.parse.status, "parsed");
});

test("layer count is derived from LAYER_CHANGE markers", async () => {
  const { parsed } = await parseFixture(completeGcode({ layers: 17 }));

  assert.equal(parsed.result.layer_count, 17);
});

test("max Z is derived from Z markers", async () => {
  const { parsed } = await parseFixture(completeGcode({ layers: 17 }));

  assert.equal(parsed.result.max_layer_z_microns, 3400);
});

test("path traversal and files outside allowed roots are rejected", async () => {
  const allowedRoot = await createFixtureRoot();
  const outsideRoot = await createFixtureRoot();
  const outsideFile = await writeGcode(outsideRoot, "outside.gcode", completeGcode());

  await assert.rejects(() => parsePrusaSlicerGcode(outsideFile, { allowedRoots: [allowedRoot] }), /escapes allowed roots/);
});

test("oversized files are rejected before parsing", async () => {
  const root = await createFixtureRoot();
  const filePath = await writeGcode(root, "oversize.gcode", completeGcode());

  await assert.rejects(
    () => parsePrusaSlicerGcode(filePath, { allowedRoots: [root], maxFileSizeBytes: 10 }),
    /exceeds max size/,
  );
});

test("tail-window expansion can find stats after a large prefix", async () => {
  const largePrefix = `${"; filler\n".repeat(180000)}`;
  const { parsed } = await parseFixture(`${largePrefix}${completeGcode()}`);

  assert.equal(parsed.result.print_time_seconds, 1496);
});

test("duration parser supports seconds, minutes, hours, and days", () => {
  assert.equal(parseDurationToSeconds("45s").seconds, 45);
  assert.equal(parseDurationToSeconds("24m 56s").seconds, 1496);
  assert.equal(parseDurationToSeconds("1h 24m 56s").seconds, 5096);
  assert.equal(parseDurationToSeconds("2h").seconds, 7200);
  assert.equal(parseDurationToSeconds("1d 2h 3m 4s").seconds, 93784);
  assert.equal(parseDurationToSeconds("2w").seconds, null);
});

test("slice params canonical JSON uses approved field order", () => {
  const json = canonicalSliceParamsJson({
    brim_width_microns: 0,
    support_mode: "none",
    fill_density_percent: 50,
    layer_height_microns: 200,
    nozzle_diameter_microns: 400,
    printer_model: "Bambu Lab P1S",
    material: "PLA",
  });

  assert.equal(
    json,
    '{"material":"PLA","printer_model":"Bambu Lab P1S","nozzle_diameter_microns":400,"layer_height_microns":200,"fill_density_percent":50,"support_mode":"none","brim_width_microns":0}',
  );
});

test("slice params order changes keep the same SHA", () => {
  const first = createSliceParamsFingerprint({
    material: "PLA",
    printer_model: "Bambu Lab P1S",
    nozzle_diameter_microns: 400,
    layer_height_microns: 200,
    fill_density_percent: 50,
    support_mode: "none",
    brim_width_microns: 0,
  });
  const second = createSliceParamsFingerprint({
    brim_width_microns: 0,
    support_mode: "none",
    fill_density_percent: 50,
    layer_height_microns: 200,
    nozzle_diameter_microns: 400,
    printer_model: "Bambu Lab P1S",
    material: "PLA",
  });

  assert.equal(first.slice_params_json, second.slice_params_json);
  assert.equal(first.slice_params_sha256, second.slice_params_sha256);
});

test("slice params value changes change the SHA", () => {
  const first = createSliceParamsFingerprint({ fill_density_percent: 50 });
  const second = createSliceParamsFingerprint({ fill_density_percent: 15 });

  assert.notEqual(first.slice_params_sha256, second.slice_params_sha256);
});
