import { test } from "node:test";
import assert from "node:assert/strict";

import {
  buildPrusaSlicerArgs,
  getPrusaSlicerConfig,
  isPrusaSlicerEnabled,
  parseGcodeMetadata,
  runPrusaSlicer,
} from "../src/backend/slicer.ts";

test("parses PrusaSlicer G-code printing time and filament weight from tail comments", () => {
  const metadata = parseGcodeMetadata(`
; random gcode
; estimated printing time (normal mode) = 1h 23m 45s
; total filament used [g] = 42.6
`);

  assert.equal(metadata.printTimeSeconds, 5025);
  assert.equal(metadata.filamentWeightG, 42.6);
  assert.equal(metadata.rawFilamentUsedG, 42.6);
  assert.equal(metadata.filamentWeightSource, "g");
});

test("converts PrusaSlicer filament length in mm to grams", () => {
  const metadata = parseGcodeMetadata(
    `
; estimated printing time = 2h 0m 0s
; filament used [mm] = 1000
`,
    "PLA",
  );
  const expectedVolumeMm3 = 1000 * Math.PI * (1.75 / 2) ** 2;
  const expectedWeightG = (expectedVolumeMm3 / 1000) * 1.24;

  assert.equal(metadata.printTimeSeconds, 7200);
  assert.equal(Number(metadata.filamentWeightG?.toFixed(4)), Number(expectedWeightG.toFixed(4)));
  assert.equal(metadata.rawFilamentUsedMm, 1000);
  assert.equal(metadata.materialDensity, 1.24);
  assert.equal(metadata.filamentWeightSource, "mm");
});

test("converts PrusaSlicer filament volume in cm3 to grams", () => {
  const metadata = parseGcodeMetadata(
    `
; estimated printing time = 35m 0s
; filament used [cm3] = 12.5
`,
    "PETG",
  );

  assert.equal(metadata.printTimeSeconds, 2100);
  assert.equal(metadata.filamentWeightG, 15.875);
  assert.equal(metadata.rawFilamentUsedCm3, 12.5);
  assert.equal(metadata.materialDensity, 1.27);
  assert.equal(metadata.filamentWeightSource, "cm3");
});

test("prefers volume-derived PETG weight over slicer gram output when volume is available", () => {
  const metadata = parseGcodeMetadata(
    `
; estimated printing time = 35m 0s
; filament used [cm3] = 12.5
; total filament used [g] = 15.5
`,
    "PETG",
  );

  assert.equal(metadata.filamentWeightG, 15.875);
  assert.equal(metadata.rawFilamentUsedG, 15.5);
  assert.equal(metadata.materialDensity, 1.27);
  assert.equal(metadata.filamentWeightSource, "cm3");
});

test("derives PLA weight from cm3 when PrusaSlicer reports zero total grams", () => {
  const metadata = parseGcodeMetadata(
    `
; estimated printing time = 4h 12m 0s
; filament used [mm] = 288034.65
; filament used [cm3] = 692.80
; total filament used [g] = 0.00
; filament_density = 0
`,
    "PLA",
  );

  assert.equal(metadata.printTimeSeconds, 15120);
  assert.equal(metadata.rawFilamentUsedCm3, 692.8);
  assert.equal(metadata.rawFilamentUsedG, 0);
  assert.equal(metadata.materialDensity, 1.24);
  assert.equal(metadata.filamentWeightSource, "cm3");
  assert.equal(Number(metadata.filamentWeightG?.toFixed(2)), 859.07);
});

test("reads PrusaSlicer filament weight in grams directly", () => {
  const metadata = parseGcodeMetadata(
    `
; estimated printing time = 10m 0s
; filament used [g] = 8.25
`,
    "ABS",
  );

  assert.equal(metadata.printTimeSeconds, 600);
  assert.equal(metadata.filamentWeightG, 8.25);
  assert.equal(metadata.rawFilamentUsedG, 8.25);
  assert.equal(metadata.materialDensity, 1.04);
  assert.equal(metadata.filamentWeightSource, "g");
});

test("returns empty metadata when PrusaSlicer G-code lacks time and weight comments", () => {
  const metadata = parseGcodeMetadata(`
; generated by PrusaSlicer
G1 X0 Y0
; no estimate footer
`);

  assert.equal(metadata.printTimeSeconds, null);
  assert.equal(metadata.filamentWeightG, null);
  assert.equal(metadata.filamentWeightSource, null);
});

test("builds PrusaSlicer command as argument array without shell concatenation", () => {
  const args = buildPrusaSlicerArgs({
    inputFilePath: "/uploads/model.stl",
    gcodeFilePath: "/tmp/model.gcode",
    material: "PLA",
    layerHeight: 0.2,
    infillDensity: 50,
    needSupport: true,
    profilePath: "/app/profiles/bambu-p1s.ini",
  });

  assert.deepEqual(args, [
    "--export-gcode",
    "--load",
    "/app/profiles/bambu-p1s.ini",
    "--output",
    "/tmp/model.gcode",
    "--filament-type",
    "PLA",
    "--layer-height",
    "0.2",
    "--fill-density",
    "50%",
    "--support-material",
    "/uploads/model.stl",
  ]);
});

test("PrusaSlicer is disabled by default and refuses execution", async () => {
  const originalEnabled = process.env.PRUSASLICER_ENABLED;

  delete process.env.PRUSASLICER_ENABLED;

  try {
    const config = getPrusaSlicerConfig();

    assert.equal(config.enabled, false);
    assert.equal(config.bin, "prusa-slicer");
    assert.equal(config.profilePath, "/app/profiles/bambu-p1s.ini");
    assert.equal(config.timeoutSeconds, 120);
    assert.equal(config.maxConcurrency, 1);
    assert.equal(isPrusaSlicerEnabled(config), false);

    await assert.rejects(
      () =>
        runPrusaSlicer({
          inputFilePath: "/uploads/model.stl",
          gcodeFilePath: "/tmp/model.gcode",
          material: "PLA",
          config,
        }),
      /PrusaSlicer is disabled/,
    );
  } finally {
    if (originalEnabled == null) {
      delete process.env.PRUSASLICER_ENABLED;
    } else {
      process.env.PRUSASLICER_ENABLED = originalEnabled;
    }
  }
});
